cakeprojects/cakeapp/urls.py
from django.urls import path
from .import views
app_name='cakeapp'

urlpatterns=[
    path('',views.home,name='home'),
    path('cake/<int:cake_id>/',views.details,name='details'),
    path('add/',views.add_cake,name='add_cake'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

cakeprojects/cakeprojects/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cakeapp.urls'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

cakeprojects/cakeapp/models.py
from django.db import models

# Create your models here.

class Cake(models.Model):
    cake_name=models.CharField(max_length=250)
    cake_flavour=models.CharField(max_length=250)
    cake_desc=models.TextField()
    cake_price=models.IntegerField()
    cake_img=models.ImageField(upload_to='cake-imges')


    def __str__(self):
        return self.cake_name

cakeprojects/cakeapp/forms.py
from django import forms
from.models import Cake

class CakeForm(forms.ModelForm):
    class Meta:
        model=Cake
        fields=['cake_name','cake_flavour','cake_desc','cake_price','cake_img']

cakeprojects/cakeapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import CakeForm
from.models import Cake

# Create your views here.

def home(request):
    cake=Cake.objects.all()
    context={
        'cake_list':cake
    }
    return render(request,'home.html',context)

def details(request,cake_id):
    cake=Cake.objects.get(id=cake_id)
    return render(request,'detail.html',{'cake':cake})

def add_cake(request):
    if request.method=='POST':
        cake_name=request.POST.get('cake_name',)
        cake_flavour=request.POST.get('cake_flavour',)
        cake_desc=request.POST.get('cake_desc',)
        cake_price = request.POST.get('cake_price',)
        cake_img = request.FILES['cake_img']
        cake=Cake(cake_name=cake_name,cake_flavour=cake_flavour,cake_desc=cake_desc,cake_price=cake_price,cake_img=cake_img)
        cake.save()

    return render(request,'add.html')

def update(request,id):
    cake=Cake.objects.get(id=id)
    form=CakeForm(request.POST or None,request.FILES,instance=cake)

    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'cake':cake})



def delete(request,id):
    if request.method=='POST':
        cake=Cake.objects.get(id=id)
        cake.delete()
        return redirect('/')
    return render(request,'delete.html')

cakeprojects/templates/add.html
{% extends 'base.html' %}
{% block body %}


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <input type="text" name="cake_name"  class="form-control"  placeholder="Enter Cake Name">
    </div>
     <div class="form-group">
        <input type="text" name="cake_flavour" class="form-control" placeholder="Enter Cake Flavour">
    </div>
    <div class="form-group">
        <input type="text" name="cake_desc"  class="form-control"  placeholder="Enter Cake Desc">
    </div>
     <div class="form-group">
        <input type="text" name="cake_price"  class="form-control"  placeholder="Enter Cake Price">
    </div>
     <div class="custom-file">
      <input type="file" name="cake_img" class="custom-file-input" id="customFile">
      <label class="custom-file-label" for="customFile">Choose file</label>
   </div><br><br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<br>
     <a class="btn btn-dark" href="{% url 'cakeapp:home' %}">Back</a>


{% endblock %}

cakeprojects/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>cake Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Cake Hunt</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-link" href="#">Features</a>
        <a class="nav-link" href="#">About</a>
        <a  class="btn btn-success" href="{% url 'cakeapp:add_cake' %}">Add Cakes</a>


    </div>
  </div>

    <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
       <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>

{% block body %}
{% endblock %}


</body>
</html>

cakeprojects/templates/delete.html
{% extends 'base.html' %}
{% block body %}


<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    <p>Are you delete this cake??</p>
   <button type="submit" class="btn btn-primary">Delete</button>
      <br><br>
     <a  class="btn btn-dark" href="{% url 'cakeapp:home' %}">Back</a>

</form>


{% endblock %}

cakeprojects/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{cake.cake_img.url}}" width="400" height="400">
        </div>
        <div class="col-md-6">
            <h3 class="text-info">{{cake.cake_name}}</h3>
            <i><b>{{cake.cake_flavour}}</b></i>
            <p>{{cake.cake_desc}}</p>
            <h6>Rs.{{cake.cake_price}}</h6><br>

            <a  class="btn btn-warning" href="{% url 'cakeapp:update' cake.id %}">Update</a><br><br>
            <a  class="btn btn-danger" href="{% url 'cakeapp:delete' cake.id %}">Delete</a>
        </div>
    </div>
    <br>
     <a  class="btn btn-dark" href="{% url 'cakeapp:home' %}">Back</a>
</div>

{% endblock %}

cakeprojects/templates/edit.html
{% extends 'base.html' %}
{% block body %}


<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Update</button>
    <br><br>
     <a  class="btn btn-dark" href="{% url 'cakeapp:home' %}">Back</a>

</form>


{% endblock %}

cakeprojects/templates/home.html
{% extends 'base.html' %}
{% block body %}

  <div class="card-deck">
      {% for i in cake_list %}
    <div class="card">
        <img src="{{i.cake_img.url}}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{i.cake_name}}</h5>
            <p class="card-text">{{i.cake_flavour}}.</p>
            <a href="{% url 'cakeapp:details'  i.id %}" class="btn btn-warning">View Details</a>

       </div>
   </div>
      {% endfor %}
 </div>

{% endblock %}